# Generated by Django 2.2.15 on 2020-10-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='currentBid',
            new_name='bidValue',
        ),
    ]
